### ISSUE TITLE
Add CWDIllegalInDllSearch setting

### ISSUE THREAD

**Issue by Harvester57** [Harvester57/Security-ADMX#10]
Harden against DLL hijacking attacks, as proposed by @Deas-h in https://github.com/Harvester57/Security-ADMX/issues/9#issuecomment-1212829775

Will probably only support 0xFFFFFFFF (enabled, DWORD = 4294967295) and 0 (disabled).

# Reference
- https://www.tenable.com/plugins/nessus/48763

**Comment by Harvester57** [comment]
Added in v 1.0.22 (https://github.com/Harvester57/Security-ADMX/releases/tag/1.0.22)

@Deas-h, could you check that it is working as expected for you ?

**Comment by Harvester57** [comment]
Closing it for now, feel free to re-open it if it's not working as intended :)

**Comment by Deas-h** [comment]
Works! Thanks for your help! :)
