### ISSUE TITLE
Confusing descriptions

### ISSUE THREAD

**Issue by SylveonBottle** [Harvester57/Security-ADMX#13]
https://github.com/Harvester57/Security-ADMX/blob/e39b07133dc8824586437ea7250d93a4088b2da4/en-US/AdditionalHardening.adml#L231

So I need to enable this policy to disable DES 56? Just checking.

**Comment by Harvester57** [comment]
Nope, enabling this policy will enable it, disabling the policy will disable it.

**Comment by SylveonBottle** [comment]
So set the policy to Disabled, to disable the user of DES 56/56?

**Comment by Harvester57** [comment]
Yes, setting the policy to Disabled will disabled support for DES 56/56, and the same logic applies to the other ciphers, protocols and hash algorithms

**Comment by Harvester57** [comment]
I updated the description for several policies, let me know if it is clearer:

https://github.com/Harvester57/Security-ADMX/compare/1.0.23...main

**Comment by SylveonBottle** [comment]
much better :+1:
