### ISSUE TITLE
WinHttp TLS 1.2 only

### ISSUE THREAD

**Issue by Deas-h** [Harvester57/Security-ADMX#16]
You currently don´t have this setting in your GPO, but I found it on a recent blog post. If we completely disable everything below TLS 1.2, I think this is missing to allow WinHttp to work only with TLS 1.2.

https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392

**Comment by Harvester57** [comment]
Good catch ! (and I read this article when it was published... :))

Will try to add the setting this weekend :)

**Comment by Harvester57** [comment]
Sorry for the delay, I added the policy in v1.0.29, can you check if everything works as expected ?

**Comment by Deas-h** [comment]
NP - seems to do what it should. Thanks for your help! :)

**Comment by Harvester57** [comment]
🎉🎉
