### ISSUE TITLE
.NET Framework 2 Strong Crypto settings wrong

### ISSUE THREAD

**Issue by Deas-h** [Harvester57/Security-ADMX#9]
When .NET Framework 2 Strong Crypro is enabled, it is displayed as Disabled in the GPO settings page. But the settings are made correct in the GPO - so the basic mechanism is correct.

![image](https://user-images.githubusercontent.com/111049416/184100026-97b37c89-c83e-471d-9922-d8ad82929d7a.png)

When searching where this could be wrong, I discovered that in the "<disabledList>" for Strong Crypto the last disabled setting has a value of 1 instead of 0.

![image](https://user-images.githubusercontent.com/111049416/184100605-dc06e994-0d57-4568-bf8d-5c363f4d1891.png)

Brgds Deas

**Comment by Harvester57** [comment]
Hi !

Thank you for reporting this bug, indeed it was a typo from my part, this is fixed in the 1.0.21 version. 

Glad to see someone using thisp roject in the wild ! :)

**Comment by Deas-h** [comment]
Hi, thanks for fixing this so quick! :)

I am glad that someone is doing this work! I used the registry section before for those settings but LGPO.exe is not able to replicate registry keys from an exported domain GPO to standaone servers. This way it will hopefully work, but I was not able to test it so far.

Would be nice if you could implement other security settings currently distributed only by registry "hack" like CWDIllegalInDllSearch.

Brgds Deas

**Comment by Harvester57** [comment]
Yeah, LGPO is able to restore standalone registry keys, but only from a PolicyRules file where you'd have manually added them, unfortunately (and it doesn't handle REG_MULTI_SZ values hezn you import from PolicyRules, it's a known bug).

We already have CWDIllegalInDllSearch in our PolicyRules file so I didn't add it in the ADMX, but i's a good idea. If you have other suggestions, I'm all ears ! :)
